// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_images.sql

package db

import (
	"context"
)

const addProductImage = `-- name: AddProductImage :one
INSERT INTO product_images (product_id, url, is_main)
VALUES ($1, $2, $3)
RETURNING id, product_id, url, is_main, created_at
`

type AddProductImageParams struct {
	ProductID int64  `json:"product_id"`
	Url       string `json:"url"`
	IsMain    bool   `json:"is_main"`
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, addProductImage, arg.ProductID, arg.Url, arg.IsMain)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const countProductImages = `-- name: CountProductImages :one
SELECT COUNT(*) FROM product_images WHERE product_id = $1
`

func (q *Queries) CountProductImages(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProductImages, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = $1 AND product_id = $2
`

type DeleteProductImageParams struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error {
	_, err := q.db.Exec(ctx, deleteProductImage, arg.ID, arg.ProductID)
	return err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, product_id, url, is_main, created_at FROM product_images WHERE id = $1 AND product_id = $2
`

type GetProductImageParams struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) GetProductImage(ctx context.Context, arg GetProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImage, arg.ID, arg.ProductID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, product_id, url, is_main, created_at FROM product_images
WHERE product_id = $1
ORDER BY is_main DESC, created_at ASC
`

func (q *Queries) GetProductImages(ctx context.Context, productID int64) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.IsMain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMainProductImage = `-- name: SetMainProductImage :exec
UPDATE product_images
SET is_main = (id = $1)
WHERE product_id = $2
`

type SetMainProductImageParams struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) SetMainProductImage(ctx context.Context, arg SetMainProductImageParams) error {
	_, err := q.db.Exec(ctx, setMainProductImage, arg.ID, arg.ProductID)
	return err
}
